// EJERCICIO 4: Función Groovy reutilizable
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}

pipeline {
  agent any

  // Se define la variable global para la imagen de herramientas
  environment {
    CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}"
  }

  stages {
    // EJERCICIO 1: Estructura básica e Información
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    // EJERCICIO 3: Construir imagen CI con make (para Java)
    stage('CI - Build tools image') {
      steps {
        script {
          echo 'Construyendo la imagen Docker de herramientas CI para Java...'
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }

    // EJERCICIO 3: Stage separado para Lint
    stage('CI - Lint') {
      steps {
        script {
          // EJERCICIO 4: Uso de la función Groovy
          runInDocker(env.CI_IMAGE_NAME) {
            echo 'Ejecutando revisión de formato de código (Lint)...'
            sh 'make lint'
          }
        }
      }
    }

    // EJERCICIO 3: Stage separado para Test
    stage('CI - Test') {
      steps {
        script {
          // EJERCICIO 4: Uso de la función Groovy
          runInDocker(env.CI_IMAGE_NAME) {
            echo 'Ejecutando tests unitarios con Maven...'
            sh 'make test'
          }
        }
      }
    }
  }
}